[project]
name = "media-compressor"
version = "0.1.0"
description = "Universal media compressor (Video + Image)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1",
    "rich>=13.9.4,<14.0.0",
    "tqdm>=4.67.3",
    "pillow>=10.2.0",
]
