[project]
name = "netease-music-playlist-song-info-extract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyncm>=1.8.1",
    "pyperclip>=1.11.0",
]
