remote=['onedrive','gdrive']

[path]
'C:\Users\Initsnow\Pictures'='Pictures'
'C:\Users\Initsnow\Documents\backups\config'='backups\config'
'C:\Users\Initsnow\Documents\backups\script'='backups\script'
'C:\Users\Initsnow\Documents\books'=['backups\books',"gdrive"]
